### ISSUE TITLE
Should try harder to delete AWS resources

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#213]
Sometimes task failures are fatal, for example:

```
TASK [roles/kraken.services : Wait for ELBs to be deleted] *********************
task path: /workspace/ansible/roles/kraken.services/tasks/kill-services.yaml:61
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/cloud/amazon/ec2_elb_facts.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1487696043.98-278874384307395 `" && echo ansible-tmp-1487696043.98-278874384307395="` echo $HOME/.ansible/tmp/ansible-tmp-1487696043.98-278874384307395 `" ) && sleep 0'
<localhost> PUT /tmp/tmpclrr3E TO /root/.ansible/tmp/ansible-tmp-1487696043.98-278874384307395/ec2_elb_facts.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487696043.98-278874384307395/ /root/.ansible/tmp/ansible-tmp-1487696043.98-278874384307395/ec2_elb_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python /root/.ansible/tmp/ansible-tmp-1487696043.98-278874384307395/ec2_elb_facts.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487696043.98-278874384307395/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_UihhU0/ansible_module_ec2_elb_facts.py", line 245, in <module>
    main()
  File "/tmp/ansible_UihhU0/ansible_module_ec2_elb_facts.py", line 237, in main
    elbs=elb_information.list_elbs())
  File "/tmp/ansible_UihhU0/ansible_module_ec2_elb_facts.py", line 209, in list_elbs
    if existing_lb.name in self.names:
TypeError: argument of type 'NoneType' is not iterable

fatal: [localhost]: FAILED! => {
    "attempts": 1, 
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ec2_elb_facts"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_UihhU0/ansible_module_ec2_elb_facts.py\", line 245, in <module>\n    main()\n  File \"/tmp/ansible_UihhU0/ansible_module_ec2_elb_facts.py\", line 237, in main\n    elbs=elb_information.list_elbs())\n  File \"/tmp/ansible_UihhU0/ansible_module_ec2_elb_facts.py\", line 209, in list_elbs\n    if existing_lb.name in self.names:\nTypeError: argument of type 'NoneType' is not iterable\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}

PLAY RECAP *********************************************************************
localhost                  : ok=24   changed=1    unreachable=0    failed=1   

rodin:k2 dwat$ 
```

When this happens we are stuck manually deleting AWS resources. Auditing the code to avoid python exceptions is the right way to fix this. However bug will always be present, so this issue is a suggestion that we add a --force-delete option to cleanup AWS resources independent of service shutdown, etc.

**Comment by davidewatson** [comment]
Another instance: ```TASK [roles/kraken.services : Wait for api server to become available in case it's not] ***
 [WARNING]: Unable to find '/root/.kraken/dewVitalogy/admin.kubeconfig' in expected paths.

fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ lookup('file', kubeconfig)|from_yaml|json_query('clusters[*].cluster.server') }}: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /root/.kraken/dewVitalogy/admin.kubeconfig"}

PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=0    unreachable=0    failed=1   

rodin:k2 dwat$ ```

**Comment by coffeepac** [comment]
@venezia will create a spec issue for a garbageman helper app, both of these issues were resolved.
