### ISSUE TITLE
Trying to run up/update with tags 'ssh-only' produces an error

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/k2#292]
Observation/History:

Was trying to verify the cluster that got stood up. I wanted to SSH into a node, however the file ssh_config was missing. I asked about this, and was told that being the last task performed, it was very likely that the task was not run because of a previous error. I proceeded to then run the sole task based on the tag: `ssh_only`

```
./up.sh -o $HOME/.kraken/ -c $HOME/.kraken/ae-cynosure_config.yaml -t 'ssh_only' -v '-vvvv'
``` 

Reproducing:

I have a config file created to bring up my own cluster, defaults remain with the addition of one more node (not special nor master nor etcd) and a volume for those nodes that can be mounted. The config file can be found here:  https://gist.github.com/alejandroEsc/fcf5845923e0dcb048be2dc772f00ecf

Results:

The following error found:
```
TASK [kraken.config : Include configuration variables from defaults file] ******
task path: /Users/escobar/Development/go/src/github.com/samsung-cnct/k2/ansible/roles/kraken.config/tasks/main.yaml:2
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 401, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/include_vars.py", line 39, in run
    source = self._loader.path_dwim_relative(self._task._role._role_path, 'vars', source)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 230, in path_dwim_relative
    if source.startswith('~') or source.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

fatal: [localhost]: FAILED! => {"failed": true, "stdout": ""}
```

Expected output:
I expected to see task run successfully and with the missing config file found.

**Comment by alejandroEsc** [comment]
In an attempt to address this, and remove dependencies on y machine, running the following:

```
 docker run $K2OPTS quay.io/samsung_cnct/k2:latest ./up.sh -o $HOME/.kraken/ -c $HOME/.kraken/ae-cynosure_config.yaml -t 'ssh_only'
```

will post results below.

**Comment by alejandroEsc** [comment]
update, success! the above command works, code ran and the expected output files from running those tags worked great!
