### ISSUE TITLE
Schema validation errors should be output a useful, concise message

### ISSUE THREAD

**Issue by lostlivio** [samsung-cnct/k2#625]
We should also wrap errors that occur during schema validation of the cluster.yaml such that it doesn't throw exceptions, but rather outputs useful messages. An example would be when a over-character limit occurs in the cluster name.  Below is an example of the exception message that currently occurs.

_An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 'TheMotherOfAllClusters'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n File "/tmp/ansible_UvKuR3/ansible_module_jsonschema.py", line 184, in \n main()\n File "/tmp/ansible_UvKuR3/ansible_module_jsonschema.py", line 180, in main\n module.fail_json(changed=False, msg="Validation failed", result=result)\n File "/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py", line 1993, in fail_json\n File "/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py", line 1973, in return_formatted\n File "/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py", line 414, in remove_values\n File "/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py", line 414, in \n File "/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py", line 414, in remove_values\n File "/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py", line 414, in \n File "/tmp/ansible_UvKuR3/ansible_modlib.zip/ansible/module_utils/basic.py", line 425, in remove_values\nTypeError: Value of unknown type: <class 'jsonschema.exceptions.ValidationError'>, 'TheMotherOfAllClusters' is too long\n\nFailed validating u'maxLength' in schema['properties']['deployment'][u'properties'][u'clusters'][u'items'][u'properties'][u'name']:\n {u'description': u'Name of this cluster.',\n u'maxLength': 13,\n u'minLength': 1,\n u'type': u'string'}\n\nOn instance['deployment'][u'clusters'][0][u'name']:\n 'TheMotherOfAllClusters'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by lostlivio** [comment]
This is duplicated by issue #623
